### ISSUE TITLE
EasyRSA issue

### ISSUE THREAD

**Issue by infiniti8** [xtrime-ru/antizapret-vpn-docker#100]
Решил запустить контейнер с нуля. При запуске docker compose возникает вот такая ошибка в логах контейнера, такое ощущение, как-будто файл Dockerfile не отрабатывает, потому что в корне не создается папка easyrsa, только если я руками склонирую репозиторий easyrsa, но даже в таком случае, в контейнере продолжают возникать такие ошибки.

```
antizapret-vpn  | 
antizapret-vpn  | Notice
antizapret-vpn  | ------
antizapret-vpn  | CA creation complete. Your new CA certificate is at:
antizapret-vpn  | * /root/easyrsa/pki/ca.crt
antizapret-vpn  | 
antizapret-vpn  | Create an OpenVPN TLS-AUTH|TLS-CRYPT-V1 key now: See 'help gen-tls'
antizapret-vpn  | 
antizapret-vpn  | Build-ca completed successfully.
antizapret-vpn  | 
antizapret-vpn  | 
antizapret-vpn  | EasyRSA version 3.2.1
antizapret-vpn  | 
antizapret-vpn  | Error
antizapret-vpn  | -----
antizapret-vpn  | Unknown command option: 'nodatetime'
```

**Comment by xtrime-ru** [comment]
Спасибо за сообщение! Судя по всему, в какой то из версии easyrsa убрали опцию nodatetime. 

Сделал фикс, попробуйте свежий образ: https://github.com/xtrime-ru/antizapret-vpn-docker/commit/7ffca0291cbedd917a558dba60a20532749553bd

**Comment by infiniti8** [comment]
да, теперь все ок, спасибо!
