### ISSUE TITLE
AdGuard home issue

### ISSUE THREAD

**Issue by infiniti8** [xtrime-ru/antizapret-vpn-docker#101]
Привет! Продолжаю тебя мучать.

Так как я не смог обойти TLS при использовании OVPN, то решил попробовать связку AdGuard+AntiZapret.

Поднял контейнеры, все настроил, с микротика интерфейс wg на сервере пингуется, как ДНС указал на микротике 77.88.8.8 по инструкции для кинетика, в журнале AdGuard вижу, что домены резолвятся, но заблокированные домены не открываются, например youtube.com. Незаблокированные домены открываются нормально.

скрин журнала AdGuard:
![Screenshot_1](https://github.com/user-attachments/assets/5136cd28-20cb-428f-861e-78af616b647b)

логи контейнера:
```
Request: [127.0.0.1:52110] (udp) / 'WWw.YoutUbe.cOm.' (AAAA)
antizapret-vpn  | Oct 09 19:52:08 dnsmap[158]: GOT AAAA or HTTPS
antizapret-vpn  | Oct 09 19:52:08 dnsmap[158]: Reply: [127.0.0.1:52110] (udp) / 'WWw.YoutUbe.cOm.' (AAAA) / RRs:
```

ip-api.com:
```
{
    "dns": {
        "geo": "Poland - i3D.net B.V",
        "ip": "188.122.80.235"
    }
}
```

nslookup youtube.com:
```
C:\Users\Administrator>nslookup youtube.com
╤хЁтхЁ:  UnKnown
Address:  192.168.0.1

Не заслуживающий доверия ответ:
╚ь :     youtube.com
Address:  10.224.0.15
```

nslookup github.com:
```
C:\Users\Administrator>nslookup github.com
╤хЁтхЁ:  UnKnown
Address:  192.168.0.1

Не заслуживающий доверия ответ:
╚ь :     github.com
Address:  140.82.121.4
```

**Comment by infiniti8** [comment]
Вот еще заметил.

```
C:\Users\Administrator>ping youtube.com

Обмен пакетами с youtube.com [10.224.0.8] с 32 байтами данных:
```

![image](https://github.com/user-attachments/assets/6ec3b413-7cf3-4ff9-ab56-ad56afee7b36)

youtube резолвится в какой-то адрес из подсети 10.224.0.0/15, адреса могут быть в разное время разные, при этом в AdGuard я вижу, что там ютуб резолвится в нормальный адрес. Может быть с сервера по какой-то причине не возвращается ответ на DNS-запрос?

**Comment by xtrime-ru** [comment]
Для заблокированных сайтов DNS (встроенный или adguard) возвращает ip в подсети 10.224.0.0/15. Дальше openvpn или wg насстроены перенаправялть трафик до этой подсети через удаленный сервер. Если у тебя не работает openvpn или WG подклбчение, то и трафику до 10.224.0.0/15 идти некуда. 

> Так как я не смог обойти TLS при использовании OVPN, то решил попробовать связку AdGuard+AntiZapret.

Я не понял что это значит. VPN работает или нет?

Если openvpn не работает, то надо использовать amnezia. Если клиента нет, то тогда wireguard, но его блокируют. 
Рекомендую попробовать сначала на ПК/телефоне проверить, что именно работает у твоего провайдера.

**Comment by infiniti8** [comment]
У меня поднялся wireguard на микротике, сетевая связность с моего микрота с адресом интерфейса ВГ 10.1.166.2 до адреса интерфейса ВГ на сервере 10.1.166.1 есть, ICMP проходит. С микротика также пингуется и адрес 10.224.0.1, а вот с ПК этот адрес не пингуется, ясное дело, что тут проблема в маршрутизации. Но если я захожу внутрь контейнера WG и добавляю маршрут до моей локальной сети 192.168.0.0/24 через 10.1.166.2 (адрес WG интерфейса микротика), то связности нет, пинг сделать не получается с ошибкой:

```
910c6271e1bc:/app# ping 192.168.0.1
PING 192.168.0.1 (192.168.0.1): 56 data bytes
ping: sendto: Required key not available
```

Все доменные имена резолвятся через AdGuard, я вижу это в его журнале, незаблокированные работают потому что резолвятся в белые адреса, которые действительно принадлежат этим доменам, а вот заблокированные резолвятся в подсеть 10.224.0.0/15, с которой есть проблема.

**Comment by infiniti8** [comment]
после добавления разрешенных адресов в docker-compose файлах и перезапуска контейнера, конфигурация WG внутри контейнера не меняется:

```
cat wg0.conf 

# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Server
[Interface]
PrivateKey = 2KvLpJDE4bzZ2cXSEgpBD/lMRJ3w=
Address = 10.1.166.1/24
ListenPort = 443
PreUp = 
PostUp =  iptables -t nat -A POSTROUTING -s 10.1.166.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 443 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; 
PreDown = 
PostDown =  iptables -t nat -D POSTROUTING -s 10.1.166.0/24 -o eth0 -j MASQUERADE; iptables -D INPUT -p udp -m udp --dport 443 -j ACCEPT; iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; 


# Client: MikroTik (0d59b07b-290d-4f96-8324-ea6700a3dfd6)
[Peer]
PublicKey = Tk3q3AQvUOTs
PresharedKey = 5mM1Wu
AllowedIPs = 10.1.166.2/32
```

**Comment by infiniti8** [comment]
нужно было просто включить маскарадинг на микротике в интерфейс ВГ
