### ISSUE TITLE
Некорректно работает регулярное выражение

### ISSUE THREAD

**Issue by dartraiden** [xtrime-ru/antizapret-vpn-docker#110]
`(?:[-\w]+\.)*myip\.com$`

Регулярка захватывает конкретный домен и любые его субдомены, помещена в include-regex-custom.txt, но домен не проксируется. Похоже, она как-то неправильно обрабатывается.

**Comment by Ernieleo** [comment]
Попробуйте заменить на `^([a-zA-Z0-9-]+\.)*myip\.com$`, у меня с ней всё заработало.
Вероятно, проблема связана с тем, как обрабатываются символы \w или конструкции (?:...).

**Comment by xtrime-ru** [comment]
Да. Под капотом для сравнения используется конструкция из bash: 

https://github.com/xtrime-ru/antizapret-vpn-docker/blob/b00efeaf5be31ed43d26d9d6869c4f5d656df979/rootfs/etc/knot-resolver/regex.sh#L7C1-L11C3

Там есть свои особенности: https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Pattern-Matching

> Within ‘[’ and ‘]’, character classes can be specified using the syntax [:class:], where class is one of the following classes defined in the POSIX standard:
> 
> alnum   alpha   ascii   blank   cntrl   digit   graph   lower
> print   punct   space   upper   word    digit
> 
> A character class matches any character belonging to that class. The word character class matches letters, digits, and the character ‘_’.

Т.е. вместо `[\w]` надо использовать `[:word:]`
