### ISSUE TITLE
Добавьте патч для Apple.

### ISSUE THREAD

**Issue by ShiGhost** [xtrime-ru/antizapret-vpn-docker#14]
https://ntc.party/t/ios-macos-openvpn/4468

**Comment by xtrime-ru** [comment]
Добавил. Просьба проверить последнюю версию!

**Comment by lu40k-tech** [comment]
По какой-то причине, перестало работать на iOS на версии выше [3.1.0](https://github.com/xtrime-ru/antizapret-vpn-docker/releases/tag/v3.1.0)
