### ISSUE TITLE
Adding custom includes/excludes makes updating complicated

### ISSUE THREAD

**Issue by nekr0z** [xtrime-ru/antizapret-vpn-docker#17]
Adding custom domains/ips to corresponding config files leads to conflicts on git pulls that need to be resolved.

Making a branch with additions and merging master into it on updates is a solution currently, but a better solution would be to add support for user-customizable config files that would not be touched by repository updates.

**Comment by xtrime-ru** [comment]
Yes, did not have time for proper solution. Will take a look after full refactoring of internals.

**Comment by xtrime-ru** [comment]
I cleaned config files and will not edit them in future.
https://github.com/xtrime-ru/antizapret-vpn-docker/releases/tag/v3.0.0
