### ISSUE TITLE
Disable option for TLS for use on Mikrotik

### ISSUE THREAD

**Issue by infiniti8** [xtrime-ru/antizapret-vpn-docker#20]
Hi!

How I can to disable TLS crypt option? Mikrotik doesnt support the use of TLS. On previous versions of the repository everything worked fine, after adding TLS it became impossible to use this container in conjunction with Mikrotik

**Comment by infiniti8** [comment]
just comment "tls-crypt keys/antizapret-tls-crypt.key 0" in docker-container openvpn conf file and remove tls-crypt from ovpn-client file like temporary solution

**Comment by xtrime-ru** [comment]
Thanks for report. I removed tls-crypt because there is not much benefits. 
In future we will add such features only with ENV variables to control them.
