### ISSUE TITLE
AdGuardHome + antizapret-vpn-docker

### ISSUE THREAD

**Issue by ShiGhost** [xtrime-ru/antizapret-vpn-docker#3]
Не могу никак объединить docker-compose с AdGuardHome + antizapret-vpn-docker. Antizapret работает только с `network_mode: "host"` из-за этого не получается настроить. Делал по аналогии как в [docker-adguard-unbound-wireguard](https://github.com/fnazz/docker-adguard-unbound-wireguard), в контейнере antizapret добавлял строку `policy.add(policy.all(policy.FORWARD({'10.2.0.100'})))` в `/etc/knot-resolver/kresd.conf`

**Comment by xtrime-ru** [comment]
Я, к сожалению, без понятия, что такое AdGuard. Можно попытать счастья в группе на офф форуме: https://ntc.party/t/vpn/129/

**Comment by xtrime-ru** [comment]
У меня кстати контейнер работает без network_mode: "host". Вероятно зависит от каких то базовых настроек системы на хостинге.

**Comment by xtrime-ru** [comment]
Если шаги надо делать при каждом старте, то есть файлик init.sh. Можно в него добавить необходимые действия.

**Comment by xtrime-ru** [comment]
> А как туда добавлять? Добавил `LANG=C.UTF-8 /root/antizapret/doall.sh` ничего не изменилось, для теста добавлял и `echo nameserver 8.8.8.8 > /etc/resolv.conf` не сработало.

Сюда: https://github.com/xtrime-ru/antizapret-vpn-docker/blob/master/init.sh#L13, перед существующими командами. 

Проверить, что выполняется - можно, например, с помощью `echo`. Результат появится во `docker-compose logs`.

Не знаю, чем помог Volumes, так как содержимое контейнера сохраняется между рестартами. Оно дропается только при пересоздании контейнера.
