### ISSUE TITLE
Не открывается msrc.microsoft.com

### ISSUE THREAD

**Issue by dartraiden** [xtrime-ru/antizapret-vpn-docker#32]
Нужно добавить msrc.microsoft.com в исключения, раз microsoft.com проксируется по умолчанию.

При этом, исключение доменов работает как-то странно.

fix.sh содержит `microsoft.com`
в exclude-hosts-custom.txt я добавил `msrc.microsoft.com`

Результат: microsoft.com не проксируется, msrc.microsoft.com проксируется, а хотелось-то наоборот.

**Comment by xtrime-ru** [comment]
В антизапрете не совсем очевидная логика. Оно собирает **домены** из строк в файлах. При этом exclude перебивает include. Получается что в обоих случаях домен microsoft и он не будет проксироваться.

Есть планы перейти на регулярки в конфиге kresd. Мб сделаю в выходные.

**Comment by dartraiden** [comment]
Там даже хуже:

- microsot.com не проксируется, т.к. он в include и exclude
- а его поддомены проксируются, т.к. базовый домен в include

**Comment by xtrime-ru** [comment]
Просьба попробовать новые regex правила https://github.com/xtrime-ru/antizapret-vpn-docker#adding-domainsips

**Comment by dartraiden** [comment]
Исходные данные: `microsoft.com` и все его поддомены прокируются, поскольку домен присутствует в https://github.com/xtrime-ru/antizapret-vpn-docker/blob/master/rootfs/root/antizapret/config/include-hosts-dist.txt

Добавил в `/config/exclude-regex-custom.txt` запись `^msrc\.microsoft\.com$`
Результат: вообще ничего не проксируется, даже домены из роскомнадзоровского реестра.

**Comment by xtrime-ru** [comment]
Нельзя оставлять пустую строку в конце файла. Иначе будет сравнивать с пустотой и под нее все подходит :) 

Сейчас сделаю фикс, что бы удалялись пустые строки.

**Comment by xtrime-ru** [comment]
Исправил:

https://github.com/xtrime-ru/antizapret-vpn-docker/commit/c2d936f82bc88c2a025e007fa7f22cd31f3efc02

Просьба проверить на последней версии контейнера.

**Comment by dartraiden** [comment]
Теперь всё работает корректно: microsoft.com со всеми поддоменами проксируется, а msrc.microsoft.com не проксируется. Спасибо!
