### ISSUE TITLE
Option to disable download az rules

### ISSUE THREAD

**Issue by xtrime-ru** [xtrime-ru/antizapret-vpn-docker#41]
1. ENV var to toggle az rules update
2. ENV var to control update interval

**Comment by Dimariqe** [comment]
Было бы полезно сделать параметр отвечающий за время обновления списка, где 0 - вообще отключение автообновления.
Как я понимаю нам нужно менять этот параметр:
https://github.com/xtrime-ru/antizapret-vpn-docker/blob/master/rootfs/etc/systemd/system/antizapret-update.timer#L5
Или вообще отключение скачивания/парсинга внешнего списка. Мне к примеру нужны только определенные ресурсы, а на 99% списки получаемые автоматически крайне бесполезны. Они просто отжирают ресурсы.
