### ISSUE TITLE
Обрывы при подключении на МГТС (Домашний интернет МТС в Москве)

### ISSUE THREAD

**Issue by Ernieleo** [xtrime-ru/antizapret-vpn-docker#46]
Столкнулся с ограничениями к подключению по TCP/UDP с клиента из Windows 11 с Москвы, провайдер МГТС к серверу расположенному в Латвии. С мобильных устройств на Android с WIFI аналогично обрывает подключение, такое поведение ранее наблюдал при использовании мобильного интернета Теле2, теперь и дома. Тест провел и в другом округе у товарища на его устройствах, ограничения по подключению аналогичны.

Проблемы при подключении впервые были замечены 21 числа на старой сборке, до рефакторинга, выполнил полную переустановку на новую версию 3.2.4, проблемы остались. Тестирование на подключение проводил с включенным и выключенным **TLS_CRYPT**, при использовании **DCO** UDP и без, с активированным имеется шанс на подключение при "передергивании" подключения. Дополнительно пробовал менять порт, не помогло, изминений нет.

Просмотрев ошибки на стороне клиента, сервера - ничего прямо похожего на ошибку не увидел, фигурирует только реконект из-за отключения. Докер был настроен в Debian 12, для исключения системной ошибки, дополнительно провёл тестирование на переустановленной системе на Ubuntu 22.04. 
Из самого докер контейнера и системы все сетевые запросы проходят, сайты и DNS доступны.

При использовании обычного OpenVPN (установщик от angristan), с базовыми настройками, проблем с подключением нет, соединение есть, без ограничений со стороны оператора и так же работает на мобильном интернете Теле2, но на всех своих устройствах Windows с 22 числа появилась проблема с отсуствие входящего трафика, DNS. Переустановка, проверка на входящие обновления и проверка актуальных проблем ясности в происходящем не прибавило.

upd. Это явление вызвано ограничениями, с Российским сервером проблем нет, всё работает исправно, вины в установщике от angristan явно нет. Вопросы к новым методам РКН, обратный трафик недоступен оказывается.

**Comment by Murakumo-JP** [comment]
Такая же проблема у моей знакомой из мск у нас сервер в германий стоит, я сам не в мск живу но на кинетики роутере всё работает а вот с приложения если тестить идёт разрыв связи всегда, как решить данную проблему так и не понял.

**Comment by xtrime-ru** [comment]
@Ernieleo Спасибо за инфу. У меня тоже МГТС и немецкий сервер. Идут реконнекты первые пару минут, но потом подключается. 

Я занимаюсь прикричиванием поддержки дополнительных прокотолов, но никаких сроков.

**Comment by alexunderboots** [comment]
Так-же периодические рекконекты на РТ (урал)

**Comment by Ernieleo** [comment]
Решение найдено, и оно самое простое — перейти на рабочий вариант VPN.
По инструкции (пропуская часть про настройку роутера, если на нём не планируете использовать VPN) выполните настройку AmneziaWG и подключитесь через клиентские приложения на ваших устройствах. Подключение аналогично OpenVPN, но на МГТС и Т2 (Теле2) всё прекрасно работает.

Инструкция: [Как выполнить установку с WireGuard (AmneziaWG)](https://github.com/xtrime-ru/antizapret-vpn-docker/blob/master/docs/guide_Keenetic_RU.md#wireguard)

Дополнительный нюанс: если будете использовать приложение от Амнезии — AmneziaVPN, возможно, возникнет баг с отсутствием маршрутизации. В таком случае на ПК скачайте приложение [amneziawg-windows-client](https://github.com/amnezia-vpn/amneziawg-windows-client). На мобильных устройствах использую AmneziaVPN с подключением через конфиг, но в случае ошибки, попробуйте убрать ранее настроенные списки туннелирования в приложении. У меня при чистой установке всё заработало сразу, без проблем.
