### ISSUE TITLE
Перестал работать 

### ISSUE THREAD

**Issue by mazixs** [xtrime-ru/antizapret-vpn-docker#5]
Дня 4 назад перестал работать, пытался обновить, но ничего не изменилось. 
Сервер удаленный в Ниндерландах, подключение происходит, но сайты выдают ERR_NAME_NOT_RESOLVED 
Публичный антизапрет работает.

**Comment by xtrime-ru** [comment]
Да, была ошибка с новым конфигом. Исправлена сегодня: https://github.com/xtrime-ru/antizapret-vpn-docker/issues/4
Просьба обновится и пересобрать контейнер: 

```shell
git pull
docker compose build
docker compose up -d
```

**Comment by mazixs** [comment]
Не исправило ситуацию, та же ошибка  ERR_NAME_NOT_RESOLVED

**Comment by xtrime-ru** [comment]
Надо проверить, работает ли kresd:
servicectl status kresd@1

**Comment by mazixs** [comment]
> Надо проверить, работает ли kresd: servicectl status kresd@1

```
root@nlserver01:~# cd antizapret
root@nlserver01:~/antizapret# docker compose down
[+] Running 2/2
 ✔ Container antizapret-vpn    Removed                                                                            10.8s
 ✔ Network antizapret_default  Removed                                                                             0.1s
root@nlserver01:~/antizapret# git fetch && git reset --hard origin/master
HEAD is now at 9d7e41b Fix: kresd config error
root@nlserver01:~/antizapret# docker compose build
[+] Building 1.1s (11/11) FINISHED                                                                       docker:default
 => [antizapret-vpn internal] load build definition from Dockerfile                                                0.0s
 => => transferring dockerfile: 1.35kB                                                                             0.0s
 => [antizapret-vpn internal] load metadata for docker.io/library/alpine:latest                                    0.9s
 => [antizapret-vpn internal] load .dockerignore                                                                   0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [antizapret-vpn builder 1/2] FROM docker.io/library/alpine:latest@sha256:c5b1261d6d3e43071626931fc004f70149ba  0.0s
 => [antizapret-vpn internal] load build context                                                                   0.0s
 => => transferring context: 29B                                                                                   0.0s
 => CACHED [antizapret-vpn builder 2/2] RUN wget https://antizapret.prostovpn.org/container-images/az-vpn/rootfs.  0.0s
 => CACHED [antizapret-vpn stage-1 1/4] COPY --from=builder /rootfs-dir /                                          0.0s
 => CACHED [antizapret-vpn stage-1 2/4] RUN wget https://secure.nic.cz/files/knot-resolver/knot-resolver-release.  0.0s
 => CACHED [antizapret-vpn stage-1 3/4] RUN cd /root/antizapret/     && git pull     && sed -i -E "s/(CHARSET=UTF  0.0s
 => CACHED [antizapret-vpn stage-1 4/4] COPY ./init.sh /                                                           0.0s
 => [antizapret-vpn] exporting to image                                                                            0.0s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:495935776ae282ed5bf75e3eff04f40ea54fedf1b63ad06d6b6217ff47a06712                       0.0s
 => => naming to docker.io/xtrime/antizapret-vpn:latest                                                            0.0s
root@nlserver01:~/antizapret# docker compose up -d
[+] Running 1/2
 ⠋ Network antizapret_default  Created                                                                             1.1s
 ✔ Container antizapret-vpn    Started                                                                             0.9s
root@nlserver01:~/antizapret# systemctl status kresd@1
Unit kresd@1.service could not be found.
root@nlserver01:~/antizapret# systemctl status kresd
Unit kresd.service could not be found.
```

**Comment by mazixs** [comment]
я пробовал с нуля поставить все, ничего не меняется.
Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-94-generic x86_64)

В логах в контейнере глухо, подключение происходит, но все сайты становятся недоступны

**Comment by xtrime-ru** [comment]
Команду нужно выполнять внутри контейнера. И надо подождать 2-5 минут после его старта: 

```
docker compose exec antizapret-vpn bash
servicectl status kresd@1
```

**Comment by mazixs** [comment]
> Команду нужно выполнять внутри контейнера. И надо подождать 2-5 минут после его старта:
> 
> ```
> docker compose exec antizapret-vpn bash
> servicectl status kresd@1
> ```

root@431c3ae311e9:~# systemctl status kresd@1
● kresd@1.service - Knot Resolver daemon
   Loaded: loaded (/lib/systemd/system/kresd@.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kresd@.service.d
           └─override.conf
   Active: activating (start) since Wed 2024-02-21 14:05:54 UTC; 3s ago
     Docs: man:kresd.systemd(7)
           man:kresd(8)
 Main PID: 43366 (kresd)
    Tasks: 1 (limit: 151)
   Memory: 317.1M
      CPU: 2.375s
   CGroup: /system.slice/system-kresd.slice/kresd@1.service
           └─43366 /usr/sbin/kresd -c /usr/lib/knot-resolver/distro-preconfig.lua -c /etc/knot-resolver/kresd.conf -n

Feb 21 14:05:54 431c3ae311e9 systemd[1]: Starting Knot Resolver daemon...
Feb 21 14:05:54 431c3ae311e9 kresd[43366]: [system] warning: hard limit for number of file-descriptors is only 65535 but recommended value is 524288

**Comment by mazixs** [comment]
Вот конфиг kresd как я понял 

```
-- Default empty Knot DNS Resolver configuration in -*- lua -*-

net.listen('127.0.0.1', 53, { kind = 'dns' })
net.listen('192.168.100.1', 53, { kind = 'dns', freebind = true })
net.listen('192.168.104.1', 53, { kind = 'dns', freebind = true })

-- Switch to unprivileged user --
user('knot-resolver','knot-resolver')
-- Unprivileged
cache.size = 100 * MB

-- For tmpfs
-- cache.open(300 * MB, 'lmdb:///tmp/knot-resolver')

-- See https://gitlab.labs.nic.cz/knot/knot-resolver/issues/470
net.ipv6 = false

modules = {
        'hints > iterate',  -- Load /etc/hosts and allow custom root hints
        'stats',            -- Track internal statistics
        'predict',          -- Prefetch expiring/frequent records
}

-- minimum TTL = 2 minutes
cache.min_ttl(120)

dofile("/etc/knot-resolver/knot-aliases-alt.conf")

policy.add(
    policy.suffix(
        policy.STUB(
            {'127.0.0.4'}
        ),
        policy.todnames(blocked_hosts)
    )
)

-- Resolve OpenNIC, EMCDNS and Namecoin domains
policy.add(
    policy.suffix(
        policy.STUB(
            {'172.104.136.243', '176.126.70.119', '87.98.175.85', '193.183.98.66'}
        ),
        policy.todnames({'bbs.', 'chan.', 'cyb.', 'dyn.', 'geek.', 'gopher.',
                         'indy.', 'libre.', 'neo.', 'null.', 'o.', 'oss.', 'oz.',
                         'parody.', 'pirate.', 'free.', 'bazar.', 'coin.',
                         'emc.', 'lib.', 'fur.', 'bit.', 'ku.', 'te.', 'ti.', 'uu.'
                         }
        )
    )
)

-- Resolve Apple
policy.add(
    policy.suffix(
        policy.FORWARD(
            {'77.88.8.8'}
        ),
        policy.todnames({'apple.com.', 'mzstatic.com.', 'akamaiedge.net.', 'edgekey.net.', 'aaplimg.com.'})
    )
)
```





```

**Comment by mazixs** [comment]
Переустановил еще раз, теперь вывод такой

```
root@nlserver01:~/antizapret# docker compose exec antizapret-vpn bash
root@28c166cf4409:/#  systemctl status kresd@1
● kresd@1.service - Knot Resolver daemon
   Loaded: loaded (/lib/systemd/system/kresd@.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kresd@.service.d
           └─override.conf
   Active: active (running) since Wed 2024-02-21 14:43:39 UTC; 7s ago
     Docs: man:kresd.systemd(7)
           man:kresd(8)
 Main PID: 310 (kresd)
    Tasks: 1 (limit: 151)
   Memory: 6.6M
      CPU: 85ms
   CGroup: /system.slice/system-kresd.slice/kresd@1.service
           └─310 /usr/sbin/kresd -c /usr/lib/knot-resolver/distro-preconfig.lua -c /etc/knot-resolver/kresd.conf -n

Feb 21 14:43:39 28c166cf4409 systemd[1]: Starting Knot Resolver daemon...
Feb 21 14:43:39 28c166cf4409 kresd[310]: [system] warning: hard limit for number of file-descriptors is only 65535 but recommended value is 524288
Feb 21 14:43:39 28c166cf4409 systemd[1]: Started Knot Resolver daemon.
```

**Comment by mazixs** [comment]
Кажется я нашел проблему, но пока не решил
```
root@28c166cf4409:/# systemctl --failed
  UNIT                                 LOAD   ACTIVE SUB    DESCRIPTION
● systemd-networkd-wait-online.service loaded failed failed Wait for Network to be Configured
```

**Comment by xtrime-ru** [comment]
У меня systemd-networkd-wait-online.service тоже не работает. Это ни на что не влияет, вероятно. 
А вот kresd@1 не запустился еще до конца. Нужно ждать запуска пару минут и мониторить логи...
У меня к сожалению логи уже ротировались, но там не должно быть ошибок. 

<img width="865" alt="Снимок экрана 2024-02-22 в 15 32 06" src="https://github.com/xtrime-ru/antizapret-vpn-docker/assets/34161928/537f0c33-a534-4b16-a5b0-2007b91b6e17">

**Comment by mazixs** [comment]
> У меня systemd-networkd-wait-online.service тоже не работает. Это ни на что не влияет, вероятно. А вот kresd@1 не запустился еще до конца. Нужно ждать запуска пару минут и мониторить логи... У меня к сожалению логи уже ротировались, но там не должно быть ошибок.
> 
> Потребление памяти kresd при нормальной работе должно быть 50-100 мбайт с пиками до 300 мбайт при загрузке/обновлении правил.
> 
> <img alt="Снимок экрана 2024-02-22 в 15 32 06" width="865" src="https://private-user-images.githubusercontent.com/34161928/306994859-537f0c33-a534-4b16-a5b0-2007b91b6e17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODE0MTIsIm5iZiI6MTcwODY4MTExMiwicGF0aCI6Ii8zNDE2MTkyOC8zMDY5OTQ4NTktNTM3ZjBjMzMtYTUzNC00YjE2LWE1YjAtMjAwN2I5MWI2ZTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA5MzgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3MTE4N2U1OGVhMGFmZjk4ZGRjZGRkYWZmMzVkZTYxMDBhNzY0NzJjMjMxOTllNjIyNGQxNTQ1ODNlYjdjMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZS6MshXLY-Br3cG9eKGPp7tLrWp-fyjtOm0IflVnVLw">


Вот вывод запущенного, не показывает никаких ошибок

```
● kresd@1.service - Knot Resolver daemon
   Loaded: loaded (/lib/systemd/system/kresd@.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kresd@.service.d
           └─override.conf
   Active: active (running) since Fri 2024-02-23 08:46:15 UTC; 54min ago
     Docs: man:kresd.systemd(7)
           man:kresd(8)
 Main PID: 3893 (kresd)
    Tasks: 1 (limit: 151)
   Memory: 63.6M
      CPU: 4.168s
   CGroup: /system.slice/system-kresd.slice/kresd@1.service
           └─3893 /usr/sbin/kresd -c /usr/lib/knot-resolver/distro-preconfig.lua -c /etc/knot-resolver/kresd.conf -n

Feb 23 08:46:11 28c166cf4409 systemd[1]: Starting Knot Resolver daemon...
Feb 23 08:46:11 28c166cf4409 kresd[3893]: [system] warning: hard limit for number of file-descriptors is only 65535 but recommended value is 524288
Feb 23 08:46:15 28c166cf4409 systemd[1]: Started Knot Resolver daemon.
```

**Comment by xtrime-ru** [comment]
Замечательно. kresd работает без ошибок. 
Что говорит команда: 
```shell
docker exec antizapret-vpn nslookup fb.com 127.0.0.1
```
```text
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
Name:	fb.com
Address: 10.224.0.5
```

**Comment by mazixs** [comment]
Вывод
```
root@28c166cf4409:/# nslookup fb.com 127.0.0.1
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   fb.com
Address: 10.224.0.1
```

**Comment by xtrime-ru** [comment]
kresd работает корректно: правила загрузились и заблокированные домены перенапрявляются во внутреннюю сеть. 

Что выдает `nslookup fb.com 192.168.100.1` на локальном компьютере? 
192.168.100.1 - это IP адрес удаленного сервера в сети, создаваемой OpenVPN.

**Comment by mazixs** [comment]
> kresd работает корректно: правила загрузились и заблокированные домены перенапрявляются во внутреннюю сеть.
> 
> Что выдает `nslookup fb.com 192.168.100.1` на локальном компьютере? 192.168.100.1 - это IP адрес удаленного сервера в сети, создаваемой OpenVPN.

Я не знаю как, но подключение на пк само по себе заработало , а в приложении на телефоне через openvpn подключается, но интернет не дает.  Пытался через termux посмотреть, но там что-то с nslookup, оно не ставится.

**Comment by mazixs** [comment]
Проблема была в модуле от magisk для изменения dns, вероятно там используется DoH

**Comment by xtrime-ru** [comment]
А как решилась эта проблема?

**Comment by mazixs** [comment]
На самом деле все ещё не решилось, происходят иногда отвалы до перезагрузки. Пока нет времени копать, попробую посмотреть лог в следующий раз.

**Comment by xtrime-ru** [comment]
Я на asuswrt сделал такой скрипт для перезапуска VPN при наличии проблем: 

```shell 
* * * * * if [ \$(nslookup fb.com 192.168.100.1 | grep 'Address 1: 10' | wc -l) -eq 0 ]; then service stop_vpnclient5; sleep 1; service start_vpnclient5; fi
```

Что-то подобное можно запихнуть и в сам контейнер при сборке. Только надо определить какой именно процесс надо рестартить. Можно запилить и стандартный healthckeck докера, но тогда сам контейнер будет рестартится, а это "дорогая" операция - старт этого контейнера очень долгий.

**Comment by mazixs** [comment]
![Screenshot_2](https://github.com/xtrime-ru/antizapret-vpn-docker/assets/13685616/61be033e-fb59-439b-9aa8-58b87b088d5a)

**Comment by xtrime-ru** [comment]
Нужен вывод top. Судя по описанию память закончилась память и сервер полез в swap. CPU ждет IO, поэтому все тормозит.
