### ISSUE TITLE
The server hangs when trying to connect

### ISSUE THREAD

**Issue by nmisha** [xtrime-ru/antizapret-vpn-docker#58]
When I try to connect to the server it hangs completely. Antizapret is running in a container. I tried enable DCO packages and without dco packages. No difference

**Comment by nmisha** [comment]
I think I found the problem. The kresd service takes away "all" the memory and loads the system. How much memory is needed to run the container?

**Comment by nmisha** [comment]
500 megabytes is not enough :(

**Comment by xtrime-ru** [comment]
Yes, kresd loads list of all blocked domains. It consumes around 300-400 Mb of RAM. Minimal requirements is 1Gb or RAM. 

There is a new ENV variable, to skip download of lists:  
```
 # EN: Do not update lists from the Internet
      # RU: Не обновлять списки из интернета
      - SKIP_UPDATE_FROM_ZAPRET=true
```

Use it and define domains manually in include.hosts.custom.txt. This will gratly reduce ram consumption
