### ISSUE TITLE
ovpn для  0.0.0.0/0

### ISSUE THREAD

**Issue by alexunderboots** [xtrime-ru/antizapret-vpn-docker#62]
Подскажите пожалуйста, как перенастроить контейнер, чтобы можно было в его ovpn заворачивать трафик?

На микротике сделана маркировка и отдельная таблица для 1.1.1.1 в ovpn-az ( 192.168.104.1 )
mtr 1.1.1.1 показывает что пакеты уходят в туннель, но не возвращаются

**Comment by xtrime-ru** [comment]
Я рекомендую для такой цели использовать Wireguard и указать в docker-compose `WG_ALLOWED_IPS=0.0.0.0/0`
https://github.com/xtrime-ru/antizapret-vpn-docker/blob/master/docker-compose.wireguard.yml#L8C9-L8C24
