### ISSUE TITLE
Client management 

### ISSUE THREAD

**Issue by MrArtemSid** [xtrime-ru/antizapret-vpn-docker#79]
Can you please add feature of adding profiles? Or it would be hard to implement in docker way?

There is an implementation in another repo, which works fine
https://github.com/GubernievS/AntiZapret-VPN/blob/main/setup/root/add-client.sh

**Comment by xtrime-ru** [comment]
We have plans to move openvpn to separate docker container with graphical interface. In same manner as wireguard/easy-wg container.  Something like https://github.com/d3vilh/openvpn-ui 

Here is discussion: https://github.com/xtrime-ru/antizapret-vpn-docker/discussions/77

**Comment by MrArtemSid** [comment]
Understand, sounds nice, thx
