### ISSUE TITLE
После обновления списка заблокированных сайтов умирает kresd

### ISSUE THREAD

**Issue by andytrofimov** [xtrime-ru/antizapret-vpn-docker#92]
Со старта он какое-то время работает, но после обновления происходит следующее:

> antizapret-vpn  | Oct 01 19:43:55 doall[223]: run build_regex.sh
> antizapret-vpn  | Oct 01 19:43:55 doall[354]: run process.sh
> antizapret-vpn  | Oct 01 19:43:55 systemd[1]: Stopping kresd@1.service - Knot Resolver daemon...
> antizapret-vpn  | Oct 01 19:43:55 systemd[1]: kresd@1.service: Deactivated successfully.
> antizapret-vpn  | Oct 01 19:43:55 systemd[1]: Stopped kresd@1.service - Knot Resolver daemon.
> antizapret-vpn  | Oct 01 19:43:55 systemd[1]: Starting kresd@1.service - Knot Resolver daemon...
> antizapret-vpn  | Oct 01 19:43:55 kresd[363]: [system] warning: hard limit for number of file-descriptors is only 65535 but recommended value is 524288
> antizapret-vpn  | Oct 01 19:43:55 kresd[363]: [system] error while loading config: /etc/knot-resolver/knot-aliases-alt.conf:33983: unexpected symbol near '$' (workdir '/var/lib/knot-resolver')
> antizapret-vpn  | Oct 01 19:43:55 systemd[1]: kresd@1.service: Main process exited, code=exited, status=1/FAILURE
> antizapret-vpn  | Oct 01 19:43:55 systemd[1]: kresd@1.service: Failed with result 'exit-code'.
> antizapret-vpn  | Oct 01 19:43:55 systemd[1]: Failed to start kresd@1.service - Knot Resolver daemon.
> antizapret-vpn  | Oct 01 19:43:55 doall[164]: Kresd rules updated
> antizapret-vpn  | Oct 01 19:43:55 systemd[1]: antizapret-update.service: Deactivated successfully.
> antizapret-vpn  | Oct 01 19:43:55 systemd[1]: antizapret-update.service: Consumed 52.916s CPU time.

Строка на которую ругается начинается с $:

> root@antizapret:~# sed '35152!d' /etc/knot-resolver/knot-aliases-alt.conf
> $'chatgpt.com\r.',

Домены на которые ругается есть в include-hosts-custom

Для воспроизведения можно использовать этот файл
https://github.com/xtrime-ru/antizapret-vpn-docker/blob/master/rootfs/root/antizapret/config/include-hosts-dist.txt

**Comment by Ernieleo** [comment]
У вас он ругается на предустановленный список?

**Comment by xtrime-ru** [comment]
Со старта контейнер использует заранее сбилженный конфиг. В фоне запускается обновление, если файлы с правилами отличаются от стандартных. 

Вы неправильно заполнили custom файлы. Исправьте ошибку или очистите файлы.
