### ISSUE TITLE
Ошибка при запуске kresd@1.service при внесении доменов в Regex

### ISSUE THREAD

**Issue by Ernieleo** [xtrime-ru/antizapret-vpn-docker#93]
При добавлении доменов в config/include-regex-custom.txt - Возникает ошибка при запуске Kresd.
Стоит всё убрать, сразу всё работает.

`Oct 01 22:03:58 systemd[1]: Failed to start kresd@1.service - Knot Resolver daemon.
Oct 01 22:14:16 systemd[1]: Starting kresd@1.service - Knot Resolver daemon...
Oct 01 22:14:16 kresd[1034]: [system] warning: hard limit for number of file-descriptors is only 65535 but recommended value is 524288
Oct 01 22:14:16 kresd[1034]: [system] error while loading config: /etc/knot-resolver/knot-aliases-alt.conf:78: unfinished string near ''(^facebook.net$' (workdir '/var/lib/knot-resolver')
Oct 01 22:14:16 systemd[1]: kresd@1.service: Main process exited, code=exited, status=1/FAILURE
Oct 01 22:14:16 systemd[1]: kresd@1.service: Failed with result 'exit-code'.`

Пример списка regex:
`^facebook\.net$
^oculuscdn\.com$
^walmart\.com$
^vcdelivery\.com$
^gamestop\.com$
^bestbuy\.com$
^target\.com$
^bbystatic\.com$
^templatemonster\.com$
^microdata\.pro$
^opencartforum\.com$
^opencartbot\.com$
^mattermost\.com$
^corrosionhour\.com$
^promods\.net$
^atlassian\.com$
^trello\.com$
^supercell\.com$
^clashofclans\.com$
^sentry\.io$
^instagram\.com$
^workplace\.com$
^oculus\.com$
^conversionsapigateway\.com$
^meta\.com$
^oculusvr\.com$
^facebookvirtualassistant\.com$
^viewpointsfromfacebook\.com$
^ads-twitter\.com$
^securecardpayment\.ru$
^plesk\.com$
^ntc\.party$
^appstore-us\.picovr\.com$
^abobe\.com$
^telegram\.org$
^t\.me$
^isekaitube\.com$
^bytegsdk\.com$
^agar\.io$
^intel\.com$
^4pda\.to$
^netflix\.com$
^redis\.com$
^code-with-me\.jetbrains\.com$
^paddle\.com$
^solidgate\.com$
^solidgate-dev\.com$
^g2a\.com$
^imagedelivery\.net$
^kamatera\.com$
^hetzner\.com$
^ionos\.com$
^nordvpn\.com$
^bard\.google\.com$
^gemini\.google\.com$`

**Comment by Ernieleo** [comment]
При добавлении доменов в обычном привычном виде в **include-hosts-custom.txt** возникает аналогичная проблема с запуском kresd

```
Oct 01 23:01:13 systemd[1]: Starting kresd@1.service - Knot Resolver daemon...
Oct 01 23:01:13 kresd[3595]: [system] warning: hard limit for number of file-descriptors is only 65535 but recommended value is 524288
Oct 01 23:01:13 kresd[3595]: [system] error while loading config: /etc/knot-resolver/knot-aliases-alt.conf:2: unexpected symbol near '$' (workdir '/var/lib/knot-resolver')
Oct 01 23:01:13 systemd[1]: kresd@1.service: Main process exited, code=exited, status=1/FAILURE
Oct 01 23:01:13 systemd[1]: kresd@1.service: Failed with result 'exit-code'.
Oct 01 23:01:13 systemd[1]: Failed to start kresd@1.service - Knot Resolver daemon.
```

**Comment by Ernieleo** [comment]
### Дополнительная информация:
Работа с файлами ведётся через WinSCP, редактирование осуществляется через Notepad++ с использованием функции "Править" в WinSCP.

### Найденное решение:

1. Войти в контейнер после авторизации на сервере через SSH, используя команду:
`docker exec -it antizapret-vpn bash`
2. Перейти в директорию antizapret/config/custom и добавить список regex доменов в файл include-regex-custom.txt.

После добавления доменов в этот список ошибок не возникло, и всё работает корректно.

**Comment by xtrime-ru** [comment]
Папка antizapret/config/custom монтируется на хост в папку ./config. Правки в контейнере и на хосте идентичны. Вероятно проблема в переводе строки в windows. Просьба прислать файл config/include-regex-custom.txt после редактирования WinSCP, который вызывает ошибку. Тогда я смогу сделать фикс для windows пользователей.

**Comment by Ernieleo** [comment]
> Папка antizapret/config/custom монтируется на хост в папку ./config. Правки в контейнере и на хосте равноценны.
> 
> Вероятно проблема в переводе строки в windows. Просьба прислать файл config/include-regex-custom.txt после редактирования WinSCP, который вызывает ошибку. Тогда я смогу сделать фикс для windows пользователей.

[include-hosts-custom.txt](https://github.com/user-attachments/files/17250196/include-hosts-custom.txt)

Вот с просто с доменами. Поведение аналогичное тому что заполню regex домены.

**Comment by xtrime-ru** [comment]
Хм... У меня все ок c этим файлов. Просьба так же прислать ваш include-regex-custom.txt
